---
# tasks file for ansible-role-clamav/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Check for EPEL repository (RedHat)"
  ansible.builtin.shell: sudo yum repolist epel* | grep -i "repolist" | awk '{ print $2 }'
  register: repo_count
  when: ansible_os_family == 'RedHat'

- name: "Set facts for install status (RedHat)"
  ansible.builtin.set_fact:
    clamav_install: true
  when: repo_count.stdout != "0" or ansible_os_family == 'Debian'

- name: "Install ClamAV packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ clamav_packages }}"
  when:
    - item|string not in ansible_facts.packages
    - clamav_install

- name: "Configure FreshClam service"
  block:
    - name: "Uncomment Logfile"
      ansible.builtin.lineinfile:
        dest: "{{ freshclam_config }}"
        regexp: "^#UpdateLogFile"
        line: "^UpdateLogFile"
        state: present
        backup: yes
