---
# tasks file for ansible-role-clamav/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Check for EPEL Repository (RedHat)"
  ansible.builtin.shell: sudo yum repolist epel* | grep -i "repolist" | awk '{ print $2 }'
  register: repo_count
  when: ansible_os_family == 'RedHat'

#- name: "Install ClamAV packages"
#  ansible.builtin.package:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ clamav_packages }}"
#  when: item|string not in ansible_facts.packages
